# Site settings
title: Compendia
email: malkarouri@tabahuth.com
description: > # this means to ignore newlines until "baseurl:"
  Entries in the Book of Knowledge
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://malkarouri.github.io" # the base hostname & protocol for your site
twitter_username: malkarouri
github_username:  malkarouri

# Build settings
markdown: kramdown
